openapi: 3.0.0
info:
  title: Excel to PDF API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /convert:
    post:
      summary: Convert Excel to PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful conversion
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
